require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'quizApplication' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'quizApplicationTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'quizApplication-tvOS' do
  # Pods for quizApplication-tvOS

  target 'quizApplication-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
